Models/ErrorViewModel.cs
namespace la_mia_pizzeria_static.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Pizza.cs
using la_mia_pizzeria_static.Validator;
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace la_mia_pizzeria_static.Models
{
    public class Pizza
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Il campo è obbligatorio")]
        [StringLength(100, ErrorMessage = "Il titolo non può essere più lungo di 100 caratteri")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Il campo è obbligatorio")]
        [StringLength(100, ErrorMessage = "La descrizione non può essere più lunga di 500 caratteri")]
        [Column(TypeName = "text")]
        [FiveWordsAttribute]
        public string Description { get; set; }

        [Required(ErrorMessage = "Il campo è obbligatorio")]
        public string Image { get; set; }

        //[Required(ErrorMessage = "Il campo è obbligatorio")]
        //[ValidateNever]
        //[IsNumberAttribute]
        //[DataType(DataType.Currency, ErrorMessage = "Il campo deve essere numerico")]
        //[Range(1, 30, ErrorMessage = "Il campo deve essere numerico")]
        public float? Cost { get; set; }
        public bool Available { get; set; }

        public Pizza()
        {

        }

        public Pizza(string name, string description, string image, float cost, bool available)
        {
            this.Name = name;
            this.Description = description;
            this.Image = image;
            this.Cost = cost;
            this.Available = available;
        }
    }
}

Controllers/HomeController.cs
using la_mia_pizzeria_static.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace la_mia_pizzeria_static.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult About()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/PizzaController.cs
using la_mia_pizzeria_static.Data;
using la_mia_pizzeria_static.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Hosting;

namespace la_mia_pizzeria_static.Controllers
{
    public class PizzaController : Controller
    {
        PizzeriaDbContext db;

        public PizzaController() : base()
        {
            db = new PizzeriaDbContext();
        }
        public IActionResult Index()
        {
            List<Pizza> listPizza = db.Pizzas.ToList();

            //qualche altra cosa...

            return View(listPizza);
        }

        public IActionResult Details(int id)
        {

            Pizza pizza = db.Pizzas.Where(p => p.Id == id).FirstOrDefault();

            return View(pizza);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Pizza pizza)
        {
            if (!ModelState.IsValid)
            {
                //return View(post);
                return View();
            }

            db.Pizzas.Add(pizza);
            db.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

Controllers/RazorController.cs
using la_mia_pizzeria_static.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace la_mia_pizzeria_static.Controllers
{
    public class RazorController : Controller
    {
        public IActionResult Snacks()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }

}

Views/Home/About.cshtml
<h1>About</h1>

<div>

    <p>Questa pizzeria nasce dall'armore verso le papere.</p>
</div>

Views/Home/Index.cshtml
<table class="table">
    <thead>
        <tr>
            <th scope="col">Nome</th>
            <th scope="col">Descrizione</th>
            <th scope="col">Foto</th>
            <th scope="col">Prezzo</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <th scope="row">Pizza Papera</th>
            <td>Una pizza ispirata alla forma della papera</td>
            <td> 
                <img src="https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/how-to-keep-ducks-call-ducks-1615457181.jpg" 
                alt="pizza" width="400" height="250">
            </td>
            <td>50€</td>
        </tr>
        <tr>
            <th scope="row">Pizza Random</th>
            <td>Riceverai una pizza a caso</td>
            <td>
                <img src="https://img.pizza/900/400"
                     alt="mmm pizza" width="400" height="250">
            </td>
            <td>5€</td>
        </tr>
        <tr>
            <th scope="row">Papera</th>
            <td>Riceverai una pizza a caso</td>
            <td>
                <img src="~/images/FWfez1SWIAEmcmO.jpg"
                     alt="mmm pizza" width="400" height="250">
            </td>
            <td>5€</td>
        </tr>
        <tr>
            <th scope="row">Pizza Random</th>
            <td>Riceverai una pizza a caso</td>
            <td>
                <img src="https://img.pizza/900/401"
                     alt="mmm pizza" width="400" height="250">
            </td>
            <td>5€</td>
        </tr>
    </tbody>
</table>

Views/Pizza/Create.cshtml
@model Pizza

<div class="container">
    <div class="row">
        <div class="col-12">
            <div class="d-flex align-items-center">
                <h1 class="mt-3 mb-3">Nuova Pizza</h1>
            </div>
            <form asp-controller="Pizza" asp-action="Create" method="post">

                @*name*@
                <div class="mb-3">
                    <strong>Titolo:</strong>
                    <input asp-for="Name" class="d-block w-100" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                @*description*@
                <div class="mb-3">
                    <strong>Contenuto:</strong>
                    <textarea asp-for="Description" rows="10" class="d-block w-100"></textarea>
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
                @*image*@
                <div class="mb-3">
                    <strong>Immagine:</strong>
                    <input asp-for="Image" class="d-block w-100" />
                    <span asp-validation-for="Image" class="text-danger"></span>
                </div>
                @*cost*@
                <div class="mb-3">
                    <strong>Costo:</strong>
                    <input asp-for="Cost" class="d-block w-100" />
                    <span asp-validation-for="Cost" class="text-danger"></span>
                </div>
                <div class="text-end">
                    <input type="submit" class="btn btn-small btn-success" value="Salva">
                </div>

            </form>
        </div>
    </div>
</div>

Views/Pizza/Details.cshtml
@model Pizza

<div class="container">
    <div class="row">
        <div class="col-12">
            <div class="d-flex align-items-center">
                <h1 class="mt-3 mb-3">Dettagli pizza</h1>
            </div>
            <div class="post-single-image-container">
                <img src="@Model.Image" alt="mmm pizza" width="900" height="400">
            </div>
            <p>
                <strong>Nome:</strong>
                @Model.Name
            </p>
            <p>
                <strong>Descrizione:</strong>
                @Model.Description
            </p>
            <p>
                <strong>Prezzo:</strong>
                @Model.Cost
            </p>
        </div>
    </div>
</div>

Views/Pizza/Index.cshtml
<h1>Home</h1>

@*Inizializzo la property Model di RazorPage *@
@model List<Pizza>

@if (Model.Count() == 0)
{
    <h3 class="text-center">Non sono presenti pizze nel menù.</h3>
}
else
{
    <table class="table">
        <thead>
            <tr>
                <th>ID</th>
                <th>Nome</th>
                <th>Descrizione</th>
                <th>Immagine</th>
                <th>Costo</th>
            </tr>
        </thead>
        <tbody>
            @foreach (Pizza pizza in Model)
            {
                @if(pizza.Available == true)
                {
                    <tr>
                        <td><a href="@Url.Action("Details",new {id = pizza.Id})">@pizza.Id</a></td>
                        <td class="title">@pizza.Name</td>
                        <td class="description">
                            @pizza.Description
                        </td>
                        <td class="image">
                            <img class="post-list-image" src="@pizza.Image" alt="mmm pizza" width="900" height="400">
                        </td>
                        <td class="price">
                            @pizza.Cost €
                        </td>
                        <td>
                            <a href="@Url.Action("Details",new {id = pizza.Id})"><button type="button" class="btn btn-info"> Dettagli Pizza </button></a>
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
}

Views/Razor/Snacks.cshtml
@{
    Layout = "_SnacksLayout";
}

<h1>Snacks</h1>

<div class="container">
    - la_mia_pizzeria_static - <a asp-area="" asp-controller="Home" asp-action="">Home</a>
</div>

<div>
    <p>Qui passerai la giornata a fare esercizi e a pensare alle papere.</p>
</div>

<div>

    <p>
        Esercizi:
        <br />
        1. Dichiarare una variabile valorizzandola con il nostro nome.
        Dichiarare un'altra variabile valorizzandola con il nostro cognome.
        Stampare il nostro nome e cognome all'interno di un tag h2.
        <br />
        2. Creare una funzione che stampa la somma dei numeri che vanno da 1 a n (con n passato come parametro - n incluso)
        Stampare dentro uno span il risultato.
        <br />
        3. Contare quante volte la lettera a è presente nalla frase "nel mezzo del cammin di nostra vita" e stampare questo valore in pagina
        <br />
        4. Creare una List int
        di 20 numeri interi (generati random da 1 a 90, 1 e 90 inclusi) e mostrare in pagina solo i numeri compresi tra 20 e 70
        <br />
        5. Stampare in pagina la data e l'ora attuale (usando la classe DateTime) con il formato anno-mese-giorno ore:minuti:secondi
        <br />
        6. Partendo dalla data di oggi (usando la classe DateTime) stampare in pagina
        <br />
        a. la data di 7 giorni fa
        <br />
        b. che giorno della settimana è oggi (il risultato dovrà essere il nome del giorno (Lunedì, Martedì, ...)
        <br />
        c. che giorno della settimana sarà nello stesso giorno e mese di oggi ma tra un anno (il risultato dovrà essere il nome del giorno (Lunedì, Martedì, ...)
    </p>
</div>

@{
    //es 1
    string name = "Sandro";
    string surname = "Ficini";

    //es 2
    int sum(int n)
    {
        int number = 1;
        for (int i = 1; i < n; i++)
        {
            number += (i + 1);
        }
        return number;
    }
    //es 3
    string sentence = "nel mezzo del cammin di nostra vita";
    int counter(string sentence, char search)
    {
        int numberChar = 0;
        foreach (char character in sentence)
        {
            if(character == search)
            {
                numberChar++;
            }
        }
        return numberChar;
    }
    //es 4
    Random rnd = new Random();
    List<int> myList = new List<int>();
    for (int j = 0; j < 20; j++)
    {
        myList.Add(rnd.Next(0, 91));
    }

    //es 5
    //vedi sotto

    //es 6
    // a
    var dt = DateTime.Today.AddDays(-7).ToString("yyyy/MM/dd");

    // b
    string dayName = DateTime.Today.DayOfWeek.ToString();

    // c
    var dayNameNextYear = DateTime.Today.AddYears(1).DayOfWeek.ToString();

}

<h2>
    <p>
        @*es 1*@
        Il mio nome è: @name.
        <br />
        Il mio cognome è: @surname.
        <br />

        @*es 2*@
        La somma dei numeri che vanno da 1 a 5 è: @sum(4).
        <br />

        @*es 3*@
        La lettera "a" è presente: @counter(sentence, 'a') volte.
        <br />

        @*es 4*@
        I numeri random compresi tra 20 e 70 sono: <br /> 
        @foreach(int number in myList)
        {
            @if(number >=20 && number <= 70)
            {
                <span>@number</span>
            }
        }
        <br />

        @*es 5*@
        La data di oggi è: @DateTime.Now.ToString("yyyy/MM/dd hh:mm:ss").
        <br />

        @*es 6*@
        @*a*@
        La data di 7 giorni fa è: @dt.
        <br />

        @*b*@
        Oggi è il giorno: @dayName.
        <br />

        @*c*@
        Il giorno di oggi tra un anno è: @dayNameNextYear
        <br />
    </p>
</h2>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - la_mia_pizzeria_static</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/la_mia_pizzeria_static.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Duckizzeria</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" href="@Url.Action("About", "Home")">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" href="@Url.Action("Snacks", "Razor")">Snacks</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" href="@Url.Action("Index", "Pizza")">Pizze</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pizza" asp-action="Create">Create</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Duckizzeria - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_SnacksLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - la_mia_pizzeria_static</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/la_mia_pizzeria_static.styles.css" asp-append-version="true" />
</head>
<body>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>